name: portfolio
description: A personal portfolio project.
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"

# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_framework: ^0.1.5
  google_fonts: any
  hexagon: ^0.2.0-nullsafety.1
  footer: ^0.0.4
  url_launcher: any
  responsive_grid: ^2.0.0
  http: ^0.13.4
#  flutter_neumorphic: any
#  flutter_polygon: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/me.jpg
    - assets/dot.png